# Generated by Django 5.2 on 2025-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_groupmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
